version: "2"
services:
  api:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app
    ports:
      - 3030:3030
    depends_on:
      - elasticsearch
    environment:
      - ELASTIC_SEARCH_HOST=http://elasticsearch:9200
    networks:
      - esnet
  elasticsearch:
    image: elasticsearch:6.8.1
    container_name: elasticsearch
    volumes:
      - "data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: kibana:6.8.1
    container_name: kibana
    hostname: kibana
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
    restart: on-failure
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
volumes:
  data:
networks:
  esnet:
